config/routes.rb
Rails.application.routes.draw do
  # get 'candidates/index'

  # get 'candidates/new'

  # get 'candidates/create'

  # get 'candidates/edit'

  # get 'candidates/update'

  # get 'candidates/destroy'

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :candidates do 
    get 'poster', on: :member
    get 'validate', on: :member
    get 'reject', on: :member
    post 'attach', on: :member
    post 'remove_attachment', on: :member
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to candidates_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://storage.googleapis.com/photos-illustration/logo-mob.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

<!-- <div><strong><%= current_user.last_name %>  <%= current_user.role.code %></strong></div>-->      
    <% if current_user.candidate.nil?%>
        <%= link_to 'Ma candidature', new_candidate_path, class:'text-nav-bar' %>  
      <% elsif !current_user.candidate.nil?%>  
        <%= link_to 'Ma candidature', candidate_path(current_user.candidate), class:'text-nav-bar'%>  
      <% end %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
      <%= link_to destroy_user_session_path, method: :delete, class:'text-nav-bar' do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Déconnexion") %>
      <% end %>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Déconnexion") %>
        <% end %>
      <% else %>
        <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>
  </div>
</div>