config/routes.rb
Rails.application.routes.draw do
  # get 'candidates/index'

  # get 'candidates/new'

  # get 'candidates/create'

  # get 'candidates/edit'

  # get 'candidates/update'

  # get 'candidates/destroy'

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :candidates do 
    get 'poster', on: :member
    get 'validate', on: :member
    get 'reject', on: :member
    post 'attach', on: :member
    post 'remove_attachment', on: :member
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  # before_validation :set_department 
  before_validation :set_status, if: :status_nil?
  has_one_attached :picture
  has_many_attached :documents
  has_many_attached :kits
  belongs_to :user
  belongs_to :district
  # belongs_to :secretary, :class_name => 'User', :foreign_key => :secretary_id
  belongs_to :election
  belongs_to :status
  has_many :audits
  has_one :deputy, dependent: :destroy
  accepts_nested_attributes_for :deputy
  validates :district, presence: true

  attr_accessor :attachment, :doc_type


  include PgSearch
  pg_search_scope :global_search,
    against: [ :profession, :mandate ],
    associated_against: {
      user:  [:first_name, :last_name]    
    },
    using: {
      tsearch: { prefix: true}
    }


 private

  def status_nil? 
    self.status.nil?
  end

  # def set_department
  #   self.department = user.department
  # end

  def set_status
    self.status = Status.find_by(code: "OPEN")
  end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy, :poster, :validate, :reject, :attach, :remove_attachment, :remove_kits_attachment, :remove_documents_attachment]

  def index
    if params[:query].nil? && params[:department].nil? && params[:status].nil?
      @candidates = policy_scope(Candidate)
      respond_to do |format|
        format.html {render}
      end
    else
      @candidates = policy_scope(Candidate) if params[:query].blank?
      unless params[:query].blank?
        if ['COM','DNF'].include? current_user.role.code
          @candidates = Candidate.global_search(params[:query])
        else
          @candidates = Candidate.global_search(params[:query]).where(district: District.where(department: current_user.department))
        end
      end
      @candidates = @candidates.where(district: District.where(department: Department.find_by(name_code:params[:department]))) unless params[:department].blank?
      @candidates = @candidates.where(status: Status.find(params[:status])) unless params[:status].blank?
      respond_to do |format|
        format.js { render partial: 'search-results' }
        format.html { render }
      end
    end
  end

  def show
    authorize @candidate
  end

  def new
    @districts = District.where(department: current_user.department)
  end

  def create
    @candidate = Candidate.new(candidate_params)
    @candidate.user = current_user
    @candidate.election = Election.find_by(name:'Législatives')
    @candidate.picture.attach(candidate_params[:picture]) unless candidate_params[:picture].nil?
    authorize @candidate
    if @candidate.save
      unless deputy_params[:last_name].empty?
        deputy = Deputy.new(deputy_params)
        deputy.candidate = @candidate
        deputy.save
      end
      redirect_to candidate_path(@candidate)
    else
      flash[:alert] = "#{@candidate.errors.full_messages.to_sentence}"
      redirect_to new_candidate_path
    end
  end

  def edit
    #watch out! We don't take current_user here as the user who edit the candidate can be a different person ex: COM modify candidate user
    @department = @candidate.district.department
    @districts = District.where(department: @department)
  end

  def update
    authorize @candidate
    @candidate.update(candidate_params)
    @candidate.picture.attach(candidate_params[:picture]) unless candidate_params[:picture].nil?
    if @candidate.save
      unless @candidate.deputy.nil?
        @candidate.deputy.update(deputy_params)
        if @candidate.deputy.save
            redirect_to candidate_path(@candidate)    
        else
          render :new
        end
      else
        deputy = Deputy.new(deputy_params)
        deputy.candidate = @candidate
        deputy.save
        redirect_to candidate_path(@candidate) 
      end
    else 
      render :new
    end  
  end

  def destroy
    @candidate.destroy
    redirect_to candidates_path
  end

  def poster
    poster = PosterService.new(@candidate)
    poster.create
    poster.attach
  end

  def validate
    authorize @candidate
    @candidate.status = Status.find_by(order: (@candidate.status.order + 1))
    Audit.create!(action: 'validate', candidate: @candidate, status: (@candidate.status) , user: current_user, validation_date: Time.now) if @candidate.save
    poster if @candidate.status.code == 'PENDING_COM'
    redirect_to candidate_path(@candidate)
  end

  def reject
    authorize @candidate
    @candidate.status = Status.find_by(order: (@candidate.status.order - 1)) 
    Audit.create!(action: 'reject', candidate: @candidate, status: (@candidate.status) , user: current_user, validation_date: Time.now) if @candidate.save
    redirect_to candidate_path(@candidate)
  end

  def attach
    doc_type = candidate_params[:doc_type]
    @candidate.send("#{doc_type}").attach(candidate_params[doc_type])
    redirect_to candidate_path(@candidate) 
  end

  def remove_attachment
    doc_type = params[:doc_type]
    @candidate.send("#{doc_type}").find(params[:attachment]).purge
    redirect_to candidate_path(@candidate) 
  end

  private

  def set_candidate
    @candidate = Candidate.find(params[:id])
  end

  def candidate_params
    params.require(:candidate).permit(:first_name, :last_name, :email, :district_id, :profession, :address, :mandate, :picture, :department, :status, :attachment, :doc_type ,documents: [], kits: [], query: [])
  end

  def deputy_params
    params.require(:candidate).require(:deputy).permit(:first_name, :last_name, :profession, :email, :address)
  end

  def user_params
    params.require(:candidate).require(:user).permit(:first_name, :last_name, :email)
  end


end

app/views/candidates/_results.html.erb
<div class="candidate-wrapper">
  <% @candidates.each do |candidate| %>
  <div class="candidate-col">
    <div class="candidate-card">
      <% if candidate.picture.attachment.nil? %>
        <%= image_tag "empty_photo.jpg", style: "background-image:linear-gradient(220deg, rgba(0, 0, 0, 0) 65%, rgba(0, 0, 0, 0.8) 90%)", class:"candidate-card-img"%>
      <% else %>
        <%= image_tag candidate.picture, style: "background-image:linear-gradient(220deg, rgba(0, 0, 0, 0) 65%, rgba(0, 0, 0, 0.8) 90%)", class:"candidate-card-img" %>
      <% end %>
        <div class="candidate-name">
          <h3 class="candidate-name-light"><%= candidate.user.first_name %></h3>
          <h3><%= candidate.user.last_name %></h3>
        </div>
        <div class="candidate-macaron status"><%= candidate.status.code %></div>
        <span></span>
        <div class="candidate-card-content">
          <span>
            <span class="circo"><%= candidate.district.num_district %>ie circonscription</span><br>
            <span><%= candidate.district.department.name_code %></span>
          </span>
        </div>
    <%= link_to "", candidate_path(candidate, :query => params[:query], :department => params[:department], :status => params[:status]), class:"candidate-card-link"%>
    </div>
  </div>
  <% end %>
</div>

 

app/views/candidates/_search-results.js.erb
function changeColor() {
  $('.status').each(function(i, obj) {
	  if (obj.innerHTML == "OPEN") 
		{obj.classList.add("green");
		obj.innerHTML = "CAN";}
	  else if (obj.innerHTML == "PENDING_SD")
	  	{obj.classList.add("orange");
		obj.innerHTML = "SD";}
	  else if (obj.innerHTML == "PENDING_DNF")
	  	{obj.classList.add("yellow");
		obj.innerHTML = "DNF";}
	  else if (obj.innerHTML == "PENDING_COM")
	  	{obj.classList.add("red");
		obj.innerHTML = "COM";}
	  else if (obj.innerHTML == "PENDING_CANDIDATE")
	  	{obj.classList.add("blue");
		obj.innerHTML = "CAN";}
	  else if (obj.innerHTML == "CLOSE")
	  	{obj.classList.add("");}	
	});
}

$(".candidate-wrapper").hide();
$(".search-results").html("<%= j(render :partial => 'results') %>");
changeColor();

app/views/candidates/edit.html.erb
<br>
<br>
<div class="col-sm-offset-4 col-sm-4">
  <div class='form-dept'><strong>Département:</strong></div> 
  <div class='form-dept input-dept form-control'><%= @department.name_code %></div> 
  <div class="form-inputs">
    <%= simple_form_for @candidate do |f| %>
      <%= f.input :district_id,
          :label => 'Circonscription',
          collection: @districts.collect {|d| [d.num_district, d.id]}.sort %>
      <%= f.input :profession %>
      <%= f.input :address, :label => 'Adresse' %>
      <%= f.input :mandate, :label => 'Mandat' %>
      <div>Photo: </div> 
      <%= f.file_field :picture %>
      <br>
    <% if @candidate.deputy.nil? %>
        <div>Suppléant:</div>
      <%= f.simple_fields_for Deputy.new do |dep| %>
          <%= dep.input :first_name, :label => 'Prénom' %>
          <%= dep.input :last_name, :label => 'Nom' %>
          <%= dep.input :profession %>
          <%= dep.input :email %>
          <%= dep.input :address, :label => 'Adresse' %>
        <% end %>
      <% else %>
        <%= f.simple_fields_for @candidate.deputy do |dep| %>
        <div>Suppléant:</div>
          <%= dep.input :first_name, :label => 'Prénom'  %>
          <%= dep.input :last_name, :label => 'Nom'  %>
          <%= dep.input :profession %>
          <%= dep.input :email %>
          <%= dep.input :address, :label => 'Adresse' %>
        <% end %>
      <% end %>
      <%= f.submit 'Valider' %>
    <% end %>
  </div>
</div>

app/views/candidates/index.html.erb
<div class= "candidates-panel">
  <div class="form-control-inline">
  <%= form_tag candidates_path, method: :get, remote: true, class:"form-tag" do %>
    <%= text_field_tag :query, params[:query], placeholder: "Prénom, nom, profession, mandat ...", class:'placeholder', id:"pg-search" %>
    <% unless ["CAN", "SD"].include? current_user.role.code  %>
      <%= text_field_tag :department, params[:department], placeholder: "Département", id: 'department-tag', class:'placeholder'%>
    <% end %>
    <%= select_tag :status, options_for_select(Status.all.collect{ |s| [s.description, s.id]}, params[:status]), :prompt => 'Statut', :onchange => "this.form.submit();", id: 'select-tag', class:'placeholder'%>
    <%= submit_tag "" %>
  <% end %>
  </div>
  <div class="search-results">
    <div class="candidate-wrapper">
      <% @candidates.each do |candidate| %>
      <div class="candidate-col">
        <div class="candidate-card">
          <% if candidate.picture.attachment.nil? %>
            <%= image_tag "empty_photo.jpg", style: "background-image:linear-gradient(220deg, rgba(0, 0, 0, 0) 65%, rgba(0, 0, 0, 0.8) 90%)", class:"candidate-card-img"%>
          <% else %>
            <%= image_tag candidate.picture, style: "background-image:linear-gradient(220deg, rgba(0, 0, 0, 0) 65%, rgba(0, 0, 0, 0.8) 90%)", class:"candidate-card-img" %>
          <% end %>
            <div class="candidate-name">
              <h3 class="candidate-name-light"><%= candidate.user.first_name %></h3>
              <h3><%= candidate.user.last_name %></h3>
            </div>
            <div class="candidate-macaron status"><%= candidate.status.code %></div>
            <span></span>
          <div class="candidate-card-content">
            <span>
              <span class="circo"><%= candidate.district.num_district %>' circonscription</span><br>
              <span><%= candidate.district.department.name_code %></span>
            </span>
          </div>
        <%= link_to "", candidate_path(candidate, :query => params[:query], :department => params[:department], :status => params[:status]), class:"candidate-card-link" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<div id="departments" class="hidden" data-departments="<%= Department.all.map {|d| d.name_code} %>"> 
</div>
<%= javascript_pack_tag 'tuning' %>
<%= javascript_pack_tag 'autocomplete' %>

app/views/candidates/new.html.erb
<br>
<br>
<div class="col-sm-offset-4 col-sm-4">
  <div>
    <div class='form-dept'><strong>Département:</strong></div> 
    <div class='form-dept input-dept form-control'><%= current_user.department.name_code %></div> 
  </div>
    <div class="form-inputs">
    <%= simple_form_for Candidate.new do |f| %>
      <%= f.input :district_id,
          :label => 'Circonscription',
          collection: @districts.collect {|d| [d.num_district, d.id]}.sort %>
      <%= f.input :profession %>
      <%= f.input :address, :label => 'Adresse' %>
      <%= f.input :mandate, :label => 'Mandat' %>
      <div>Photo: </div> 
      <%= f.file_field :picture %>
      <br>
      <div>Suppléant:</div>
      <br>
      <%= f.simple_fields_for Deputy.new do |dep| %>
        <%= dep.input :first_name, :label => 'Prénom'  %>
        <%= dep.input :last_name, :label => 'Nom'  %>
        <%= dep.input :profession %>
        <%= dep.input :email %>
        <%= dep.input :address, :label => 'Adresse'  %>
      <% end %>
      <%= f.submit 'Valider' %>
    <% end %>
  </div>
</div>

app/views/candidates/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class='cand-wrapper'>
        <div class="header-candidate">
          <% unless current_user.role.code == "CAN" %>
            <%= link_to candidates_path(:query => params[:query], :department => params[:department], :status => params[:status]) do %>
            <i class="fas fa-arrow-left"></i>
            <% end %>
          <% end %>
          <div class="candidate-status"><%= @candidate.status.description %></div>
        </div>
      </div>
        <div class='banner-candidate' style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://storage.googleapis.com/photos-illustration/AN.jpg');">
          <div class="district-header"><strong><%= @candidate.district.num_district %>' circonscription</strong></div>
          <div class="district-header"><strong><%= @candidate.district.department.name %></strong></div>
          <% if !@candidate.picture.attachment.nil? %>
            <%= image_tag @candidate.picture, class:"candidate-img" %>
          <% else %>
            <%= image_tag "empty_photo.jpg", class:"candidate-img" %>
          <% end %>
        </div>
      <div class='cand-wrapper'>
        <div class="text-cand" >
          <div class="candidate"><strong><%= @candidate.user.first_name %> <%= @candidate.user.last_name %></strong></div>
          <div> <strong> Profession: </strong><%= @candidate.profession %></div>
          <div><strong> Courriel: </strong><%= @candidate.user.email %></div>
          <div><strong>Mandat: </strong><%= @candidate.mandate %></div>
          <div><strong>Adresse: </strong><%= @candidate.address %></div>
          <% unless @candidate.deputy.nil? %>
          <div class='deputy'>Suppléant: <strong><%= @candidate.deputy.first_name %> <%= @candidate.deputy.last_name %></strong></div>
            <div><strong>Profession: </strong><%= @candidate.deputy.profession %></div>
            <div><strong>Courriel: </strong><%= @candidate.deputy.email %></div>
            <div><strong>Adresse: </strong><%= @candidate.deputy.address %></div>
          <% end %>
        </div>
        <div class="files">
          <% if current_user.role.code == 'COM' && @candidate.status.order > 3%>
            <strong>Fichiers Indesign:</strong></br>
            <% if @candidate.documents.attached? %>
              <% @candidate.documents.each do |document| %>
                <%= link_to document.filename, document, target: '_blank' %>
                <% if current_user.role.code == 'COM'%>
                  <%= link_to '', remove_attachment_candidate_path(@candidate, attachment: document.id, doc_type: 'documents'), method: :post, class: "fas fa-trash-alt"%> <br>
                 <% end %>   
              <% end %>
            <% end %>
          <a class="fas fa-plus-circle add-doc"> Ajouter</a>
          <div class="hidden">
            <%= simple_form_for @candidate, :url => attach_candidate_path, method: :post do |cand| %>
              <%= cand.file_field :documents, multiple: true, id: "input-add-doc" %>
               <%= cand.hidden_field :doc_type, :value => 'documents' %>
              <%= cand.submit id: 'btn-input-add-doc' %>
            <% end %>
          </div>
        <% end %>
        <br>
        <br>
        <% if @candidate.status.order > 3 %>
          <strong>Kit de campagne:</strong></br>
          <% @candidate.kits.each do |kit| %>
            <%#= image_tag kit.preview(resize_to_limit: [100, 100]) if kit.previewable?%>
            <%#= image_tag kit.variant(resize_to_limit: [100, 100]) if ['image/jpeg', 'image/png'].include? kit.content_type%>
            <%= link_to kit.filename, kit, target: '_blank'%> 
            <% if current_user.role.code == 'COM'%>
              <%= link_to '', remove_attachment_candidate_path(@candidate, attachment: kit.id, doc_type: 'kits'), method: :post, class: "fas fa-trash-alt"%></br>
            <% end %>  
          <% end %>
          <a class="fas fa-plus-circle add-kit"> Ajouter</a>
          <div class="hidden">
            <%= simple_form_for @candidate, :url => attach_candidate_path, method: :post do |cand| %>
              <%= cand.file_field :kits, multiple: true, id: "input-add-kit" %>
              <%= cand.hidden_field :doc_type, :value => 'kits' %>
              <%= cand.submit id: 'btn-input-add-kit'  %>
            <% end %>
           </div>
         <% end %>
        </div>
       <div class="button">
        <% if @candidate.status.code == 'OPEN' %>
          <%= link_to "#{@candidate.status.next_action}", validate_candidate_path(@candidate), class: "btn btn-success but" %>
          <%= link_to 'Modifier', edit_candidate_path(@candidate), class: "btn btn-primary but" %>
        <% elsif @candidate.status.code == 'PENDING_SD' && (current_user.role.code == 'DNF' || current_user.role.code == 'SD' || current_user.role.code == 'COM')%>  
          <%= link_to "#{@candidate.status.next_action}", validate_candidate_path(@candidate), class: "btn btn-success but" %>
          <%= link_to "Refuser", reject_candidate_path(@candidate), class: "btn btn-warning but" %>
          <%= link_to 'Modifier', edit_candidate_path(@candidate), class: "btn btn-primary but" %>
        <% elsif @candidate.status.code == 'PENDING_DNF' && (current_user.role.code == 'DNF' || current_user.role.code == 'COM') %>
          <%= link_to "#{@candidate.status.next_action}", validate_candidate_path(@candidate), class: "btn btn-success but" %>
          <%= link_to "Refuser", reject_candidate_path(@candidate), class: "btn btn-warning but" %>
          <%= link_to 'Modifier', edit_candidate_path(@candidate), class: "btn btn-primary but" %>
        <% elsif @candidate.status.code == 'PENDING_COM' && current_user.role.code == 'COM' %>
          <%= link_to "#{@candidate.status.next_action}", validate_candidate_path(@candidate), class: "btn btn-success but" %>
          <%= link_to "Renvoyer", reject_candidate_path(@candidate), class: "btn btn-warning but" %>
          <%= link_to 'Modifier', edit_candidate_path(@candidate), class: "btn btn-primary but" %>
        <% elsif @candidate.status.code == 'PENDING_CANDIDATE' && current_user == @candidate.user %> 
          <%= link_to "#{@candidate.status.next_action}", validate_candidate_path(@candidate), class: "btn btn-success but" %>
          <%= link_to "Renvoyer", reject_candidate_path(@candidate), class: "btn btn-warning but" %>
        <% end %>
      </div>   
      <% if @candidate.audits.any? %>
        <div class="audit">
          <strong>Audit:</strong>
          <% @candidate.audits.sort.reverse.each do |audit| %>
            <div class="audit-text"><%= audit.validation_date.strftime("Validé le %d/%m/%Y à %I:%M%p")%> par <%= audit.user.first_name%> <%= audit.user.last_name%> (<%= audit.user.role.code %>)<br>
                  Status: <%= audit.status.code %> <br>
            </div>
          <% end  %>
        </div>
      <% end %>
      </div>  
    </div>
  </div>
</div>
<%= javascript_pack_tag 'tuning_show' %>